// vue-example/src/App.vue
<template>
  <Main msg="Welcome to Your Vue.js + TypeScript App"/>
  <ProductList :on-select-product="handleAddToCart"/>
  <p v-if="basketService">Items on basket: {{basket.items.length}}</p>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Main from './components/Main.vue'
import ProductList from '@/components/ProductList.vue'
import { Product } from '@domain/models/product.model'
import { basketService } from '@/services/basket.service'
import { Basket } from '@domain/models/basket.model'

type DataProps = {
  basket: Basket|null;
}

export default defineComponent({
  name: 'App',
  components: {
    Main,
    ProductList
  },
  methods: {
    handleAddToCart (product: Product) {
      this.basket = basketService.addProductToBasket(product, this.basket)
    }
  },
  data (): DataProps {
    return {
      basket: null
    }
  },
  mounted () {
    this.basket = null
  }
})
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// react-example/src/components/App.tsx
import {useState} from 'react';
import {ProductList} from '@/components/ProductList';
import {Basket} from '@domain/models/basket.model';
import {Product} from '@domain/models/product.model';
import {basketService} from '@/services/basket.service';

export default function App({msg}: {
    msg: string
}) {
    const [basket, setBasket] = useState<Basket | null>(null);

    const handleAddToCart = (product: Product) => {
        setBasket(basketService.addProductToBasket(product, basket));
    };

    return (
        <div className="App">
            <h1>{msg}</h1>
            <ProductList onSelectProduct={handleAddToCart}/>
            {basket && <p>Items on basket: {basket.items.length}</p>}
        </div>
    );
}
