// vue-example/src/components/ProductList.vue
<template>
  <ul>
    <li v-for="product in products " :key="product.id">
      <button @click="() => { onSelectProduct(product) }">{{ product.title }}</button>
    </li>
  </ul>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { productService } from '@/services/product.service'
import { Product } from '@domain/models/product.model'

type DataProps = {
  products: Product[];
}

export default defineComponent({
  name: 'ProductList',
  props: {
    onSelectProduct: { type: Function }
  },
  data (): DataProps {
    return {
      products: []
    }
  },
  mounted () {
    productService.getProducts().then(response => (this.products = response))
  }
})
</script>

// react-example/src/components/ProductList.tsx
import * as React from 'react';
import {useEffect, useState} from 'react';
import {Product} from '@domain/models/product.model';
import {productService} from '@/services/product.service';


export function ProductList({onSelectProduct}: {
  onSelectProduct: (product: Product) => void
}) {
  const [products, setProducts] = useState<Product[]>([]);

  useEffect(() => {
    productService.getProducts().then(setProducts);
  }, []);

  return (
      <ul>
        {products.map((product) => <li key={product.id}>
          <button onClick={() => {
            onSelectProduct(product);
          }}>{product.title}</button>
        </li>)}
      </ul>
  );
}
